attack_name: square_attack

# Core hyperparameters
norm: inf  # {inf, 2}
max_iter: 200
eps: 5.0               # ~10% del rango típico de features PCA ([-40,40] → rango=80)
p_init: 0.5
nb_restarts: 15
batch_size: 128
verbose: true
